/* config.js — Disability Awareness@Work deployment settings
   Generated by the admin panel. Place beside index.html and upload to your
   deployment. Editing here by hand is fine too; keep the structure intact. */
window.DAW_CONFIG = {
  videoSrc: 'intro.mp4',
  videoTitle: 'A message from Singapore before you begin',
  videoCaptions: 'intro.vtt',
  videoSkip: false,
  logoMain: 'inclusionedge.png',
  reportCC: 'completions@inclusionedge.com',
  goatcounter: '',
  goatcounterUrl: '',
  accessDays: 30,
  nameMandatory: true,
  passThreshold: 5,
  enableSetcode: false,
  adminHash: '6cc7fd7751127e88',
  orgs: [
    { hash:'1c76617fe62e6f3e', label:'Demo Org', email:'reports@example.com', logo:'' }
  ]
};
