/* ==========================================================
   Disability Awareness@Work — Final knowledge check (10 items)
   6 knowledge (2 per LO) · 3 situational · 1 application.
   Loaded by index.html as a plain <script> tag — no build step.
   Each item: {lo, q, options:[...], answer: <index of correct
   option>, why}. For a select-all-that-apply item instead, use
   {type:'checkbox', lo, q, options:[...], answer:[indices...], why}.
   The harness shuffles option order per attempt automatically.
   ========================================================== */
window.DAW_QUIZ = [

  /* --- KNOWLEDGE \u00b7 LO1 \u00b7 Understanding disability types (Module 2) --- */
  {lo:'Knowledge \u00b7 LO1', q:'Disability in Singapore is broadly grouped into four types. Which list is correct?', options:['Physical disability, sensory impairment, intellectual disability, autism','Physical, mental illness, chronic illness, autism','Sensory, learning, mobility, speech','Visible disabilities and invisible disabilities'], answer:0, why:'The four broad groups are physical disability, sensory impairment (hearing and vision), intellectual disability, and autism. Mental health conditions are a related but separate area, with separate support and guidance.'},
  {lo:'Knowledge \u00b7 LO1', q:'The autism spectrum is best pictured as\u2026', options:['A straight line running from mild to severe','A spiderweb \u2014 communication, sensory processing, social interaction and routine, with each person sitting differently on each strand','A clinical grade assigned at diagnosis','A childhood phase that fades in adulthood'], answer:1, why:'Two people with the same diagnosis can have opposite profiles \u2014 one untroubled by noise but overwhelmed by bright light, another exactly the reverse. A spectrum is not a ranking. Meet the person, not the label.'},

  /* --- KNOWLEDGE \u00b7 LO2 \u00b7 Everyday practice (Module 3) --- */
  {lo:'Knowledge \u00b7 LO2', q:'A colleague who is hard of hearing did not catch what you said. What works best?', options:['Repeat the same words, more loudly','Say it again in different words, with your face visible','Give up and send a message later','Ask another colleague to pass it on'], answer:1, why:'Rephrase, do not repeat \u2014 and keep your face visible. Raising your volume rarely helps and often distorts speech. If the huddle itself is the problem, fix the huddle: one voice at a time, faces up.'},
  {lo:'Knowledge \u00b7 LO2', q:'You are walking with a colleague who is blind to an unfamiliar part of the building. What is correct practice?', options:['Take hold of an arm and steer the way','Offer your arm, let your colleague take it, and describe the route as you walk','Walk ahead and give directions over your shoulder','Hold onto a shoulder from behind and guide'], answer:1, why:'Offer \u2014 never grab, steer or push. Your colleague takes your arm or elbow, and you narrate the space (\u201cthree steps down, then a left\u201d) so a mental map can be built. Being specific out loud is the whole skill.'},

  /* --- KNOWLEDGE \u00b7 LO3 \u00b7 Assumptions (Module 4) --- */
  {lo:'Knowledge \u00b7 LO3', q:'Why is it a problem to tell a colleague with a disability: \u201cYou are so inspiring, just for turning up to work\u201d?', options:['It is not a problem \u2014 encouragement is always welcome','It treats ordinary competence as heroism, marks the colleague as different, and quietly lowers the bar being set','It is only a problem if said in public','It is fine, provided the person seems pleased'], answer:1, why:'This is the inspiration trap. Praise the work, as you would for anyone. Praising someone simply for existing at work says: I did not expect this of you \u2014 which is the opposite of being equally recognised.'},
  {lo:'Knowledge \u00b7 LO3', q:'A colleague with a disability is struggling with a task. What is the disciplined first move?', options:['Assume the disability is the cause \u2014 it is the obvious explanation','Rule out the ordinary causes first: unclear instructions, workload, a system change, a rough week','Say nothing and quietly redo the work','Suggest the role is reduced'], answer:1, why:'When anyone else struggles we look at workload, instructions or a change in the system. Apply the same reasoning here. Very often the real cause is something in the environment \u2014 which means it is something that can be fixed.'},

  /* --- SITUATIONAL x3 --- */
  {lo:'Situational', q:'At a noisy shift huddle, two colleagues start talking over each other while facing away. Danish, who is deaf, has clearly stopped following. You are not the one running the huddle. What do you do?', options:['Nothing \u2014 it is not your huddle, and speaking up would be awkward','Stand beside Danish and whisper a running summary','Say out loud: \u201cSorry \u2014 one at a time, and can we face the group? Hard to follow otherwise.\u201d','Recap the whole briefing for Danish afterwards'], answer:2, why:'Three seconds, no authority required, and nobody is singled out \u2014 \u201chard to follow otherwise\u201d is simply true of a noisy huddle. Whispering summaries and recapping later both leave the broken briefing untouched, and cast one colleague as a permanent exception to be managed.'},
  {lo:'Situational', q:'At the staff canteen, a colleague turns to you \u2014 not to Wei Lin, who is sitting right there \u2014 and asks loudly, \u201cSo what does she like to eat, ah?\u201d What is the best response?', options:['Answer on Wei Lin\u2019s behalf \u2014 it is quicker and avoids an awkward pause','Redirect gently: \u201cWei Lin, what are you having today?\u201d','Explain Wei Lin\u2019s disability to the colleague afterwards','Say nothing \u2014 it would embarrass everyone'], answer:1, why:'Talking about a person who is sitting right there is one of the most corrosive habits in this space. One redirection, three words long, hands the conversation back to the person it belongs to \u2014 and the whole dynamic corrects itself.'},
  {lo:'Situational', q:'Priya, a colleague, confides that she has sudden hearing loss and asks you to keep it to yourself. You can see the noisy verbal handover is the real problem. What do you do?', options:['Keep the secret and say nothing further \u2014 a promise is a promise','Tell the supervisor about her hearing loss, so support can be arranged properly','Suggest writing the handover on the board, and ask Priya how \u2014 and by whom \u2014 she would like anything else raised','Tell a couple of trusted colleagues, so the team can look out for her'], answer:2, why:'Fix what is fixable (a written handover helps the whole team), keep the confidence, and hand the decision back to the person it belongs to. Passing it to a supervisor or to colleagues \u2014 however kindly meant \u2014 is still disclosing information that was never yours to share.'},

  /* --- APPLICATION x1 --- */
  {lo:'Application', q:'Your team is replacing spoken shift briefings with a new mobile app. A colleague on the team is blind. Applying what this course has taught, what is the best first step?', options:['Assume it will be fine \u2014 an app is text, and text can be read aloud by technology','Keep giving spoken briefings to that one colleague, and use the app for everyone else','Ask the colleague whether the app works with a screen reader, and what would work best \u2014 then adjust before rolling it out','Ask HR to purchase specialist software before mentioning the change to anyone'], answer:2, why:'Ask \u2192 Listen \u2192 Adjust, applied to something new. Assuming access invites failure; a separate arrangement for one person is exclusion with extra steps; and going to HR before speaking to your colleague skips the only real expert. Ask first, then involve HR if equipment or funding is genuinely needed.'}
];
